### ISSUE TITLE
problems with using RateLimiter.

### ISSUE THREAD

**Issue by SetAres** [David-Desmaisons/RateLimiter#14]
Hello! For some time I have problems with using RateLimiter. When my program starts up, everything works fine, but after a while the RateLimiter stops working. The code in the debugger stops at the line 
 `await _Semaphore.WaitAsync(cancellationToken);` of the method. 
```
        public async Task<IDisposable> WaitForReadiness(CancellationToken cancellationToken)
        {
            await _Semaphore.WaitAsync(cancellationToken);
            var count = 0;
            var now = _Time.GetNow();
            var target = now - _TimeSpan;
            LinkedListNode<DateTime> element = _TimeStamps.First, last = null;
            while ((element != null) && (element.Value > target))
            {
                last = element;
                element = element.Next;
                count++;
            }

            if (count < _Count)
                return new DisposeAction(OnEnded);

            Debug.Assert(element == null);
            Debug.Assert(last != null);
            var timeToWait = last.Value.Add(_TimeSpan) - now;
            try
            {
                await _Time.GetDelay(timeToWait, cancellationToken);
            }
            catch (Exception)
            {
                _Semaphore.Release();
                throw;
            }

            return new DisposeAction(OnEnded);
        }

```

Further, the debugger does not work, although at startup everything is fine.

**Comment by David-Desmaisons** [comment]
@SetAres from what you describe it seems that ratelimiter reach its limit and needs to wait to proceed till the next execution. At first glance nothing abnormal here, this is the way it is intended.
You can you the cancelation token in this case.

**Comment by SetAres** [comment]
> @SetAres из того, что вы описываете, похоже, что ratelimiter достигает своего предела и должен ждать до следующего выполнения. На первый взгляд, здесь нет ничего необычного, так оно и задумано. 
> Вы можете вы токен аннулирования в этом случае.

The problem is that my limiter is configured as 10 - 15 requests per second. Those. long delay should not be. For me, I repeat, at first everything works exactly as it should, but at some point the code goes into waiting as described above. (As an option, I will try to use the cancel token to solve the problem).
In my opinion, the problem appeared after updating Windows server 2016, where my program works with your library.

Is a deadlock possible if your library is used improperly (using the async / await mechanism)?

This problem may occur after loading the memory or the CPU 100%.

**Comment by David-Desmaisons** [comment]
> Is a deadlock possible if your library is used improperly (using the async / await mechanism)?
There is no such a problem that I am aware of.

> This problem may occur after loading the memory or the CPU 100%.
Maybe this is the main problem here: the system has not any CPU left to process in correct time.

Could you share a stack trace of the corresponding problem?
If you could create a minimal program to reproduce the issue , that would definitivelly help.

**Comment by David-Desmaisons** [comment]
Are you using Wait on the Tasks returned by RateLimiter?
This may cause deadlock.
