### ISSUE TITLE
How to use RateLimiter to call api? 

### ISSUE THREAD

**Issue by inventivethinking11** [David-Desmaisons/RateLimiter#16]
The example does not fit well with the actual API calling. In the scenario where API limits 5 calls per second but itself responds back in 3-4 seconds the example code just performs one call per second since its waiting for previous call to finish. How can I remedy it. 

Example code 
 
` 
 

            //Create Time constraint: max five times by second
            var timeconstraint = TimeLimiter.GetFromMaxCountByInterval(5, TimeSpan.FromSeconds(1));
            //Use it
            for (int i = 0; i < 1000; i++)
            {
                await timeconstraint.Perform(ConsoleIt);
            }

          
        private async Task ConsoleIt()
        {
            Console.WriteLine(string.Format("{0:MM/dd/yyy HH:mm:ss.fff}", DateTime.Now));
            await Task.Delay(3000); //simulate api call made and waiting for response. 
        }`

**Comment by David-Desmaisons** [comment]
You do not need to wait for the call completion:

```
for (int i = 0; i < 1000; i++)
        {
            await timeconstraint.Perform(ConsoleIt);
        }

 private void ConsoleIt()
    {
        Console.WriteLine(string.Format("{0:MM/dd/yyy HH:mm:ss.fff}", DateTime.Now));
        Thread.Sleep(3000); //simulate api call made and waiting for response. 
    }`
```

**Comment by inventivethinking11** [comment]
That does not seem to solve the problem. If you happen to execute this code, the system only makes a single call and waits until that finishes and starts next call. 

`
public async Task<bool> Start()
        {

            //Create Time constraint: max five times by second
            var timeconstraint = TimeLimiter.GetFromMaxCountByInterval(5, TimeSpan.FromSeconds(1));
            //Use it
            for (int i = 0; i < 1000; i++)
            {
                await timeconstraint.Perform(ConsoleIt);
            }

            return true;
        }
        private Task ConsoleIt()
        {
            Console.WriteLine(string.Format("{0:MM/dd/yyy HH:mm:ss.fff}", DateTime.Now));
            Thread.Sleep(3000); //simulate api call made and waiting for response. 
            Console.WriteLine("Finished");
            return Task.FromResult(0);

        }
`

**Comment by David-Desmaisons** [comment]
Note that in my example, I was using a signature with a void return and not a Task, this is key here not to wait to the completion of the task.
So:


```
for (int i = 0; i < 1000; i++)
        {
            await timeconstraint.Perform(ConsoleIt);
        }

 private void ConsoleIt()
    {
        Task.Run(() => {
         Console.WriteLine(string.Format("{0:MM/dd/yyy HH:mm:ss.fff}", DateTime.Now));
        Thread.Sleep(3000); //simulate api call made and waiting for response. 
     });
}
```

**Comment by inventivethinking11** [comment]
Oh you are right. I didn't notice, that solved the issue. 

Thanks!
