### ISSUE TITLE
Basic usage broken

### ISSUE THREAD

**Issue by Danie-Brink** [David-Desmaisons/RateLimiter#18]
The basic usage example no longer works ... on the  line:
`await timeConstraint;`
VS shows an error: _'TimeLimiter' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'TimeLimiter' could be found._

**Comment by David-Desmaisons** [comment]
Add
```
using ComposableAsync;
```
