### ISSUE TITLE
Upgrading from 1.1.1 to 2.1.0 Perform no longer available.

### ISSUE THREAD

**Issue by micahsdad1402** [David-Desmaisons/RateLimiter#23]
Upgrading from 1.1.1 to 2.1.0 it failed to compile because perform was not found

I simply changed this to enqueue. Yet to test, but couldn't find any documentation that identified the required change when you upgraded.

**Comment by David-Desmaisons** [comment]
You are correct I didn´t write any documentation with the breaking changes. Hopefully this issue will help to document them (this is the only one).
