### ISSUE TITLE
Issues using the library in a .NET Standard 2.1 & .NET Core 3.1 project

### ISSUE THREAD

**Issue by Nihlus** [David-Desmaisons/RateLimiter#25]
When attempting to use the library in a .NET Standard 2.1 or .NET Core 3.1 project that uses IAsyncDisposable (for example, asynchronous disposal of a stream), the project fails to build with a `CS0518` error.

```
  Program.cs(21, 17): [CS0518] Predefined type 'System.IAsyncDisposable' is not defined or imported
```
```cs
namespace Scratchpad
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var rateLimiter = TimeLimiter.GetFromMaxCountByInterval(1, TimeSpan.FromSeconds(1));

            for (var i = 0; i < 10; ++i)
            {
                await using var ms = new MemoryStream();

                await rateLimiter;
                Console.WriteLine(DateTime.UtcNow);
            }
        }
    }
}
```

Adding .NET Standard 2.1 as an additional target for the library should correct the issue, allowing it to natively understand duck-typed IAsyncDisposable types.

**Comment by IanKemp** [comment]
Seems like this project is abandoned. You're likely to be better off forking it and adding the NS2.1 TFM.

**Comment by David-Desmaisons** [comment]
@IanKemp The project is not abandoned....
Just give me some time please.
