### ISSUE TITLE
Limiter to Reject Requests While Resource is Unavailable -- Theory of Approach?

### ISSUE THREAD

**Issue by jboarman** [David-Desmaisons/RateLimiter#5]
@David-Desmaisons @FireNero 

How feasible would it be to write a limiter for this library that would reject new requests until the resource becomes again available?

If it's straightforward, I'd be willing to give it a try.  However, I wouldn't want to embark on that if it doesn't sound like a good application of this library.

What are your thoughts?  What advice would you give or any theories for how one my approach a rejection limiter?

**Comment by David-Desmaisons** [comment]
Hello @jboarman , I am not sure about this request.
Current philosophy is to instanciate a timeConstrainst with the current time limitation and using it to await a task.

Rejecting new request as you suggest will defeat the current solution of creatin a task to await execution as weither the action will execute synchroneously or will be "cancelled" synchroneously .

You can kind of mimic what you have in mind by passing to the `IRateLimiter` `Perform` a Cancellation token that will expire after a fixed amount of time, 100ms for example.
