### ISSUE TITLE
was restored using .net framework instead of the project target framework

### ISSUE THREAD

**Issue by ppman** [David-Desmaisons/RateLimiter#8]
@David-Desmaisons 
Sorry if it's a stupid question, but I'm new to this..

After I installed the package, using nuget in visual studio community, I'm getting this error:

package 'RateLimit 1.1.0' was restored using .NetFramework version=v4.6.1 instead of the project target framework .NetCoreApp version=v2.0 this package may not be fully compatible with your project

I'm using .net core project.
does that mean that I can't use the package in .net core?

**Comment by David-Desmaisons** [comment]
@ppman , RateLimiter current version is not campatible with .Net core. I will take a look at PR opened to make it compatible with .Net standard.

**Comment by David-Desmaisons** [comment]
@ppman corrected in version 1.1.1 of the library.
